apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-configmap
data:
  db_jdbc_url: "jdbc:postgresql://blog-postgres-svc:5432/postgres"
  email_host: "blog-mailpit-svc"
  email_port: "1025"
  redis_host: "blog-redis-svc"
  redis_port: "6379"
  rabbitmq_host: "blog-rabbitmq-svc"
  rabbitmq_port: "5672"
  metrics_export_url: "http://blog-otel-lgtm-svc:4318/v1/metrics"
  traces_export_url: "http://blog-otel-lgtm-svc:4318/v1/traces"
  logs_export_url: "http://blog-otel-lgtm-svc:4318/v1/logs"
---
apiVersion: v1
kind: Secret
metadata:
  name: blog-secrets
type: Opaque
stringData:
  db_username: "postgres"
  db_password: "postgres"
